### ISSUE TITLE
Support for Bootstrap command

### ISSUE THREAD

**Issue by escarbor** [youyo/aws-cdk-github-actions#18]
Are there any plans in supporting the `cdk bootstrap` command? Unlike most of the cdk cli commands, `bootstrap` expects an Environment as its argument rather than a Stack. Since this Action defaults by appending a `*` to the end of each command, it causes the execution to fail. [Docs](https://docs.aws.amazon.com/cdk/latest/guide/tools.html#cli)

Thanks!

**Comment by jackchi** [comment]
The failure I get is:
`No environments were found when selecting across ["*"]`

**Comment by cd17822** [comment]
I think I found a workaround for now:

```yml
     - name: cdk bootstrap
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'bootstrap'
          cdk_stack: 'aws://<account id>/<region>'
```
