### ISSUE TITLE
/bin/sh: yarn: not found

### ISSUE THREAD

**Issue by mdhornet90** [youyo/aws-cdk-github-actions#33]
This is happening during a pretty vanilla run with this tool on a github box (NOT self-hosted). Confirmed that `yarn` is installed, and the failing step in question:

```
- name: Preview Changes
   uses: youyo/aws-cdk-github-actions@v2
   with:
     working_dir: infrastructure
     cdk_subcommand: diff
     cdk_stack: application-${{ env.ENV_NAME }}
     actions_comment: false
```
