### ISSUE TITLE
actions_comment not working with cdk diff

### ISSUE THREAD

**Issue by mettke** [youyo/aws-cdk-github-actions#45]
Hey, thank you for creating this github action, it really helps us with our deployment flow. We are, however, not able to get the `actions_comment` flag to work, would you mind helping us with it?

In our yaml file we are setting the permissions:
```yaml
permissions:
  contents: write
  pull-requests: write
```

And then we use the following (AWS credentials are available via env variables):

```yaml
      - name: CDK diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          cdk_stack: 'stackname-*'
          working_dir: './infra'
          actions_comment: true
```

This creates a diff for the two stacks we have and prints out the differences (the first one has differences, the second ones doesn't), but no message is written to the PR. Could it be that it works only with one stack at a time?

```
Stack stack-name-1
IAM Statement Changes
[...]
Resources
[+] AWS::Events::Rule [..]

Stack stack-name-2
There were no differences
```
