### ISSUE TITLE
Support operations on multiple stacks

### ISSUE THREAD

**Issue by matthewmrichter** [youyo/aws-cdk-github-actions#60]
I'd like to do a diff on a few different stacks but it is unnecessarily time consuming to run the diff (or any cdk action really) as multiple jobs, when cdk itself supports running multiple at once eg: `cdk diff web api` 

It would be nice if the `cdk_stack` attribute would support multiple values. EG:

```
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "diff"
          cdk_stack:
            - web
            - api
```
