### ISSUE TITLE
Cannot find module typscript

### ISSUE THREAD

**Issue by iDVB** [youyo/aws-cdk-github-actions#9]
Not sure why I'm getting this...

```
name: cfn-xregion-bucket

on:
  push:
    branches:
      - feat-*

jobs:
  build-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: AWS CDK GitHub Actions
        uses: youyo/aws-cdk-github-actions@v1.1.4
        with:
          cdk_subcommand: deploy
          args: -c STAGE=${GITHUB_REF##*/} --require-approval never
          cdk_version: "1.42.0"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
```
